global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - compute_metrics.rules
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['192.168.1.17:9100', 'localhost:9090']
