{
 "title": "Machine",
 "description": "Dashboard to get an overview of one Linux server.\r\n",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "server", "query": "label_values(up,instance)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*(node_memory_MemFree_bytes{instance=\"$server\",job=\"prometheus\"})/node_memory_MemAvailable_bytes{instance=\"$server\",job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Min Free disk space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*min(node_filesystem_free_bytes{instance=\"$server\"}/node_filesystem_size_bytes{instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "System load normalized",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\",job=\"prometheus\"}/scalar(count(node_cpu_seconds_total{instance=\"$server\",mode=\"user\",job=\"prometheus\"}))",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$server\",job=\"prometheus\"}/scalar(count(node_cpu_seconds_total{instance=\"$server\",mode=\"user\",job=\"prometheus\"}))",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}/scalar(count(node_cpu_seconds_total{instance=\"$server\",mode=\"user\"}))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Mountpoint usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_filesystem_free_bytes/node_filesystem_size_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "More Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} ",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "MemFree"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$server\"}",
     "legendFormat": "MemSwapped"
    }
   ]
  },
  {
   "title": "CPU busy %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\"}[1m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk Space available, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(min by (mountpoint) (node_filesystem_avail_bytes{instance=~\"$server\"}/node_filesystem_size_bytes{fstype !~ \"rpc_pipefs\",device!=\"/etc/auto.misc\",mountpoint !~ \"/boot|/net|/selinux\",instance=~\"$server\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "min by (mountpoint) (node_filesystem_avail_bytes{instance=~\"$server\", mountpoint != \"/net\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IO Latency per device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_write_time_seconds_total{instance=~\"$server\"}[1m])+irate(node_disk_read_time_seconds_total{instance=~\"$server\"}[1m]))/(irate(node_disk_reads_completed_total{instance=~\"$server\"}[1m])+irate(node_disk_writes_completed_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (rate(node_disk_written_bytes_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{device}} bytes written"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Data transfer by NIC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "received {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "transmitted  {{device}}"
    }
   ]
  }
 ]
}